# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcst < Formula
  desc "A command-line utility making Minecraft server creation quick and easy for beginners."
  homepage "https://github.com/Arama0517/MCST"
  version "1.3.0"
  license "GPL-v3"

  depends_on "aria2"

  on_macos do
    on_intel do
      url "https://github.com/Arama0517/MCST/releases/download/v1.3.0/MCST-1.3.0-darwin-amd64.tar.gz"
      sha256 "6caf81cc3827e7a7344a0d1ef76e71d1b2d507898b37871144ba32f4ca62f087"

      def install
        bin.install "MCST"
        bash_completion.install "completions/MCST.bash" => "MCST"
        zsh_completion.install "completions/MCST.zsh" => "_MCST"
        fish_completion.install "completions/MCST.fish"
        man1.install "manpages/MCST.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Arama0517/MCST/releases/download/v1.3.0/MCST-1.3.0-darwin-arm64.tar.gz"
      sha256 "beda54737c765eceff468a575829e4b2a8f58ba19af77d21d2487e1de1521d3a"

      def install
        bin.install "MCST"
        bash_completion.install "completions/MCST.bash" => "MCST"
        zsh_completion.install "completions/MCST.zsh" => "_MCST"
        fish_completion.install "completions/MCST.fish"
        man1.install "manpages/MCST.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arama0517/MCST/releases/download/v1.3.0/MCST-1.3.0-linux-amd64.tar.gz"
        sha256 "ca4de998412124fb43e1537f8c674806826713481d2aba12160a775df7636957"

        def install
          bin.install "MCST"
          bash_completion.install "completions/MCST.bash" => "MCST"
          zsh_completion.install "completions/MCST.zsh" => "_MCST"
          fish_completion.install "completions/MCST.fish"
          man1.install "manpages/MCST.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Arama0517/MCST/releases/download/v1.3.0/MCST-1.3.0-linux-armv7.tar.gz"
        sha256 "925ac9391f2801ae94fb2b29807c1f3875ae04354712dee12c0ab72e439fb285"

        def install
          bin.install "MCST"
          bash_completion.install "completions/MCST.bash" => "MCST"
          zsh_completion.install "completions/MCST.zsh" => "_MCST"
          fish_completion.install "completions/MCST.fish"
          man1.install "manpages/MCST.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arama0517/MCST/releases/download/v1.3.0/MCST-1.3.0-linux-arm64.tar.gz"
        sha256 "c6e24d7f551f93e270405ece51b1bfaf609470b24b6e46c3fe5c97d5dd1eac3f"

        def install
          bin.install "MCST"
          bash_completion.install "completions/MCST.bash" => "MCST"
          zsh_completion.install "completions/MCST.zsh" => "_MCST"
          fish_completion.install "completions/MCST.fish"
          man1.install "manpages/MCST.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/MCST -v"
  end
end
