# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcst < Formula
  desc "A command-line utility making Minecraft server creation quick and easy for beginners."
  homepage "https://github.com/Arama0517/MCServerTool"
  version "1.2.0"
  license "GPL-v3"

  depends_on "aria2"

  on_macos do
    on_intel do
      url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Darwin_x86_64.tar.gz"
      sha256 "baa0beb46d6414e8cd7777eed832021fe79eaf749b335db291d6988e9596b981"

      def install
        bin.install "MCST"
        bash_completion.install "completions/MCST.bash" => "MCST"
        zsh_completion.install "completions/MCST.zsh" => "_MCST"
        fish_completion.install "completions/MCST.fish"
        man1.install "manpages/MCST.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Darwin_arm64.tar.gz"
      sha256 "95ea2e63d05774fe5bcc4a264fca29130b508d8fcc1fbc4d4787fd46a48c71ad"

      def install
        bin.install "MCST"
        bash_completion.install "completions/MCST.bash" => "MCST"
        zsh_completion.install "completions/MCST.zsh" => "_MCST"
        fish_completion.install "completions/MCST.fish"
        man1.install "manpages/MCST.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Linux_x86_64.tar.gz"
        sha256 "befa764ec0bddcdd98bccdb1709056488318381f021a4cacbb274f42c6182024"

        def install
          bin.install "MCST"
          bash_completion.install "completions/MCST.bash" => "MCST"
          zsh_completion.install "completions/MCST.zsh" => "_MCST"
          fish_completion.install "completions/MCST.fish"
          man1.install "manpages/MCST.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Linux_armv7.tar.gz"
        sha256 "65891cbd23fa6d370a3aaf54df4cd6f918b79c8acf518bb4fe6f90e3167df820"

        def install
          bin.install "MCST"
          bash_completion.install "completions/MCST.bash" => "MCST"
          zsh_completion.install "completions/MCST.zsh" => "_MCST"
          fish_completion.install "completions/MCST.fish"
          man1.install "manpages/MCST.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Linux_arm64.tar.gz"
        sha256 "b613fe7fdbc9a030f1a5c8795a62c6733720b265202b82697456d3f797657bc8"

        def install
          bin.install "MCST"
          bash_completion.install "completions/MCST.bash" => "MCST"
          zsh_completion.install "completions/MCST.zsh" => "_MCST"
          fish_completion.install "completions/MCST.fish"
          man1.install "manpages/MCST.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/MCST -v"
  end
end
