# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcst < Formula
  desc "A command-line utility making Minecraft server creation quick and easy for beginners."
  homepage "https://github.com/Arama0517/MCServerTool"
  version "1.2.0"
  license "GPL-v3"

  depends_on "aria2"

  on_macos do
    on_intel do
      url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Darwin_x86_64.tar.gz"
      sha256 "572f9fd3254f841b3beb0a66e8e6d985303191dfb09f1219c9260832dfa5c247"

      def install
        bin.install "MCST"
        bash_completion.install "completions/MCST.bash" => "MCST"
        zsh_completion.install "completions/MCST.zsh" => "_MCST"
        fish_completion.install "completions/MCST.fish"
        man1.install "manpages/MCST.1.gz"
      end
    end
    on_arm do
      url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Darwin_arm64.tar.gz"
      sha256 "3d63b38c819a3295da51630414a92883ccf1ef56d3412eb3e7dceee61e2028dc"

      def install
        bin.install "MCST"
        bash_completion.install "completions/MCST.bash" => "MCST"
        zsh_completion.install "completions/MCST.zsh" => "_MCST"
        fish_completion.install "completions/MCST.fish"
        man1.install "manpages/MCST.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Linux_x86_64.tar.gz"
        sha256 "a90cbe0fdf4c971a112ba53b936723330e39fe57292eedc8148bc7f80539064b"

        def install
          bin.install "MCST"
          bash_completion.install "completions/MCST.bash" => "MCST"
          zsh_completion.install "completions/MCST.zsh" => "_MCST"
          fish_completion.install "completions/MCST.fish"
          man1.install "manpages/MCST.1.gz"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Linux_armv7.tar.gz"
        sha256 "1a78ca8473cbd897306035c407fd146bdcf23b7ba4a86dfa9f655e3f6d2c45b3"

        def install
          bin.install "MCST"
          bash_completion.install "completions/MCST.bash" => "MCST"
          zsh_completion.install "completions/MCST.zsh" => "_MCST"
          fish_completion.install "completions/MCST.fish"
          man1.install "manpages/MCST.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arama0517/MCST/releases/download/v1.2.0/MCST_Linux_arm64.tar.gz"
        sha256 "0bd017db0f0c6ad834692a78e89925eea72d43436ae8037a42d9f8bd2393ff1e"

        def install
          bin.install "MCST"
          bash_completion.install "completions/MCST.bash" => "MCST"
          zsh_completion.install "completions/MCST.zsh" => "_MCST"
          fish_completion.install "completions/MCST.fish"
          man1.install "manpages/MCST.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/MCST -v"
  end
end
